name: CI/CD Pipeline

# Triggers da pipeline
on:
  # Executa em todos os commits (push)
  push:
    branches:
      - "**" # Todas as branches

  # Executa em pull requests
  pull_request:
    branches:
      - master

  # Webhook do Contentful - para quando o CMS for atualizado
  repository_dispatch:
    types: [contentful-update]

  # ⚠️ ATENÇÃO: DESLIGAR DEPOIS DE VALIDAR! ⚠️
  # Executa às 00:00 de todos os dias da semana (segunda a sexta)
  # Aguardar próxima segunda-feira às 00:00 UTC para validar que funciona (2 da manhã em Portugal)
  # DEPOIS: Remover toda a secção "schedule" para economizar minutos do GitHub Actions
  # ════════════════════════════════════════════════════════════════════════
  # schedule:
  #  - cron: "0 0 * * 1-5" # 00:00 UTC, segunda a sexta-feira
  # ════════════════════════════════════════════════════════════════════════
  # TODO: APAGAR AS LINHAS 20-26 APÓS VALIDAR O TRIGGER SCHEDULE

  # Permite execução manual
  workflow_dispatch:

# Permissões necessárias para o workflow
permissions:
  contents: read
  pull-requests: write
  statuses: write

# Cancelar execuções anteriores da mesma branch (otimização)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1: Code Quality Checks (run in parallel)
  prettier-check:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npx prettier --check .

  eslint-check:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload test coverage (GitHub feature)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/
          retention-days: 30

  # Job 2: Build (depends on all checks passing)
  build:
    name: Build Project
    needs: [prettier-check, eslint-check, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
          CONTENTFUL_REVALIDATE_SECRET: ${{ secrets.CONTENTFUL_REVALIDATE_SECRET }}

  # Job 3: Deploy (apenas na branch master e se tudo passar)
  deploy:
    name: Deploy to Netlify
    needs: build
    runs-on: ubuntu-latest
    # Só corre deploy na branch master E se todos os jobs anteriores passaram
    if: github.ref == 'refs/heads/master' && success()
    environment:
      name: production
      url: ${{ steps.deploy.outputs.deploy-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project for deployment
        run: npm run build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
          CONTENTFUL_REVALIDATE_SECRET: ${{ secrets.CONTENTFUL_REVALIDATE_SECRET }}

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        id: deploy
        run: |
          netlify deploy --prod --dir=.next --message="Deploy from GitHub Actions - ${{ github.sha }}" > deploy-output.txt
          echo "deploy-url=$(grep -o 'https://[^ ]*' deploy-output.txt | head -1)" >> $GITHUB_OUTPUT
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Comment deployment URL on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Deployed to: ${{ steps.deploy.outputs.deploy-url }}'
            })

      - name: Send Discord notification - Deploy Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "✅ Deploy Successful",
                "description": "Website deployed to production",
                "color": 3066993,
                "fields": [
                  {"name": "Repository", "value": "${{ github.repository }}", "inline": true},
                  {"name": "Branch", "value": "${{ github.ref_name }}", "inline": true},
                  {"name": "Commit", "value": "`${{ github.sha }}`", "inline": false},
                  {"name": "Author", "value": "${{ github.actor }}", "inline": true},
                  {"name": "Deploy URL", "value": "${{ steps.deploy.outputs.deploy-url }}", "inline": false}
                ],
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'"
              }]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord notification - Deploy Failed
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "❌ Deploy Failed",
                "description": "Deployment to production failed",
                "color": 15158332,
                "fields": [
                  {"name": "Repository", "value": "${{ github.repository }}", "inline": true},
                  {"name": "Branch", "value": "${{ github.ref_name }}", "inline": true},
                  {"name": "Commit", "value": "`${{ github.sha }}`", "inline": false},
                  {"name": "Author", "value": "${{ github.actor }}", "inline": true},
                  {"name": "Logs", "value": "[View Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})", "inline": false}
                ],
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'"
              }]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

  # Job 4: Lighthouse CI (performance, accessibility, SEO)
  lighthouse:
    name: Lighthouse CI
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Lighthouse CI
        run: npm run lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Lighthouse results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30

      - name: Send Discord notification - Lighthouse Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "🔍 Lighthouse Analysis Complete",
                "description": "Performance analysis finished successfully",
                "color": 3447003,
                "fields": [
                  {"name": "Repository", "value": "${{ github.repository }}", "inline": true},
                  {"name": "Branch", "value": "${{ github.ref_name }}", "inline": true},
                  {"name": "Website", "value": "https://tdw-mp1-henrique-policarpo.netlify.app", "inline": false},
                  {"name": "Results", "value": "[View Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})", "inline": false}
                ],
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'"
              }]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord notification - Lighthouse Failed
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "⚠️ Lighthouse Analysis Failed",
                "description": "Performance analysis did not meet thresholds",
                "color": 15105570,
                "fields": [
                  {"name": "Repository", "value": "${{ github.repository }}", "inline": true},
                  {"name": "Branch", "value": "${{ github.ref_name }}", "inline": true},
                  {"name": "Logs", "value": "[View Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})", "inline": false}
                ],
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'"
              }]
            }' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
